### ISSUE TITLE
[1.17.1] Server Crash

### ISSUE THREAD

**Issue by 0gp** [DaFuqs/Artis#15]
I can not starrt my server with Artis.
```
[11:26:31] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'artis'!
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
	at net.minecraft.server.Main.main(Main:97) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-server-launch.jar:0.10.2]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/ColorProviderRegistry
	at io.github.alloffabric.artis.ArtisResources.registerDataForTable(ArtisResources.java:59) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.Artis.registerTable(Artis.java:90) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.Artis.registerTable(Artis.java:67) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.ArtisData.loadEntries(ArtisData.java:74) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.ArtisData.loadConfig(ArtisData.java:45) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.Artis.onInitialize(Artis.java:99) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.ColorProviderRegistry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at io.github.alloffabric.artis.ArtisResources.registerDataForTable(ArtisResources.java:59) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.Artis.registerTable(Artis.java:90) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.Artis.registerTable(Artis.java:67) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.ArtisData.loadEntries(ArtisData.java:74) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.ArtisData.loadConfig(ArtisData.java:45) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at io.github.alloffabric.artis.Artis.onInitialize(Artis.java:99) ~[artis-recrafted-2.1.1+1.17.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 16 more
```

**Comment by 0gp** [comment]
sorry, I've now downgraded to Java 16 and now it works.

**Comment by 0gp** [comment]
I was able to find the reson, it was the Color Parameter in the Config.
