### ISSUE TITLE
[1.18.1 Crash] Cannot launch on a server

### ISSUE THREAD

**Issue by itsdinkd** [DaFuqs/Artis#6]
```java
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'artis'!
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.1.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.1.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.1.jar:?]
        at net.minecraft.server.Main.main(Main:106) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.1.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.1.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/ColorProviderRegistry
        at io.github.alloffabric.artis.ArtisResources.registerDataForTable(ArtisResources.java:59) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.Artis.registerTable(Artis.java:90) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.Artis.registerTable(Artis.java:67) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.ArtisData.loadEntries(ArtisData.java:74) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.ArtisData.loadConfig(ArtisData.java:45) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.Artis.onInitialize(Artis.java:99) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.1.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.ColorProviderRegistry
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.13.1.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at io.github.alloffabric.artis.ArtisResources.registerDataForTable(ArtisResources.java:59) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.Artis.registerTable(Artis.java:90) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.Artis.registerTable(Artis.java:67) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.ArtisData.loadEntries(ArtisData.java:74) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.ArtisData.loadConfig(ArtisData.java:45) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at io.github.alloffabric.artis.Artis.onInitialize(Artis.java:99) ~[artis-recrafted-2.1.1+1.18.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.1.jar:?]
        ... 15 more
```

**Comment by DaFuqs** [comment]
Ty for reporting that. This will be an easy fix.
I will upload a fixed version later today.
