### ISSUE TITLE
using a modded block as a table is impossible ?

### ISSUE THREAD

**Issue by Chuunkyz** [DaFuqs/Artis#9]
i get this (seems related to more villagers i know but same with other mods)

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'morevillagers-fabric'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$gli000$catchFabricInit(class_310.java:26978)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:block / morevillagers:blueprint_table] at different raw IDs (2632, 10047)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$ede000$setPre(class_2370.java:650)
	at net.minecraft.class_2370.method_31051(class_2370.java)
	at net.minecraft.class_2370.method_10273(class_2370.java:66)
	at net.minecraft.class_2348.method_10273(class_2348.java:27)
	at net.minecraft.class_2370.method_10272(class_2370.java:97)
	at net.minecraft.class_2378.method_39197(class_2378.java:424)
	at net.minecraft.class_2378.method_10230(class_2378.java:420)
	at io.github.pheonixvx.morevillagersfabric.init.ModBlocks.initBlocks(ModBlocks.java:26)
	at io.github.pheonixvx.morevillagersfabric.MoreVillagersFabric.onInitialize(MoreVillagersFabric.java:31)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 13 more

when i do this :

    "morevillagers:blueprint_table": {
      "type": "existing_block",
      "width": 3,
      "height": 3,
      "color": "#0058B4" 
    }

seems to work just with vanilla blocks...

**Comment by DaFuqs** [comment]
Fixed. I updated the examples at https://github.com/DaFuqs/Artis-Recrafted/wiki/Custom-Table-Examples

**Comment by Chuunkyz** [comment]
i know this is possible now, however like i said there's an issue when using a block from more villagers mod (maybe all other mods ?)
using the vanilla fletching table works, but not a modded block
